//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirQualityAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirQualityRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AirQualityRecord()
        {
            this.Alerts = new HashSet<Alert>();
        }
    
        public int RecordID { get; set; }
        public int CityID { get; set; }
        public int PollutantID { get; set; }
        public int CategoryID { get; set; }
        public int AQIValue { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual AQICategory AQICategory { get; set; }
        public virtual City City { get; set; }
        public virtual Pollutant Pollutant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alert> Alerts { get; set; }
    }
}
