//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirQualityAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertNote
    {
        public int AlertID { get; set; }
        public int NoteNo { get; set; }
        public string NoteText { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Alert Alert { get; set; }
    }
}
