//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirQualityAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticulatePollutant
    {
        public int PollutantID { get; set; }
        public string ParticleType { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Pollutant Pollutant { get; set; }
    }
}
