//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirQualityAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pollutant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pollutant()
        {
            this.AirQualityRecords = new HashSet<AirQualityRecord>();
        }
    
        public int PollutantID { get; set; }
        public string PollutantName { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirQualityRecord> AirQualityRecords { get; set; }
        public virtual GasPollutant GasPollutant { get; set; }
        public virtual ParticulatePollutant ParticulatePollutant { get; set; }
    }
}
