//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirQualityAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawAirQualityImport
    {
        public int ImportRowID { get; set; }
        public string CountryName { get; set; }
        public string CityName { get; set; }
        public Nullable<int> AQIValue { get; set; }
        public string AQICategory { get; set; }
        public Nullable<int> CO_AQIValue { get; set; }
        public string CO_AQICategory { get; set; }
        public Nullable<int> Ozone_AQIValue { get; set; }
        public string Ozone_AQICategory { get; set; }
        public Nullable<int> NO2_AQIValue { get; set; }
        public string NO2_AQICategory { get; set; }
        public Nullable<int> PM25_AQIValue { get; set; }
        public string PM25_AQICategory { get; set; }
        public System.DateTime LastUpdated { get; set; }
    }
}
