//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirQualityAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AirQualityRecordDetails
    {
        public int RecordID { get; set; }
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public int CityID { get; set; }
        public string CityName { get; set; }
        public int PollutantID { get; set; }
        public string PollutantName { get; set; }
        public int AQIValue { get; set; }
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public System.DateTime RecordLastUpdated { get; set; }
    }
}
